version: '3.1'

services:
  db:
    image: mysql
    container_name: moneta-flow-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'moneta_flow'
      MYSQL_USER: 'moneta_flow'
      MYSQL_PASSWORD: 'Bk55yc1u0eiqga6e'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 5432:3306
    networks:
      - db

  read-db:
    image: mongo
    container_name: moneta-flow-read-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "moneta_flow"
      MONGO_INITDB_ROOT_PASSWORD: "0sW6pg5Yj0ylM{iy"
    volumes:
      - database-read:/data/db
    ports:
      - 27017:27017
    networks:
      - read-db
    
  event-bus:
    image: rabbitmq:3.8-management
    container_name: moneta-flow-event-bus
    environment:
      RABBITMQ_DEFAULT_USER: "moneta_flow"
      RABBITMQ_DEFAULT_PASS: "Bk55yc1u0eiqga6e"
    volumes:
      - event-bus:/var/lib/rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - event-bus

  api:
    container_name: api
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    command:
      - "pnpm"
      - "dev"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - read-db
      - event-bus
    networks:
      - db
      - read-db
      - event-bus
    
  command-handler:
    container_name: command-handler
    build: ./backend
    env_file:
      - ./backend/.env
    command:
      - "pnpm"
      - "dev:command-handler"
    volumes:
      - ./backend:/app
    depends_on:
      - api
      - event-bus
    networks:
      - db
      - read-db
      - event-bus
  
  query-handler:
    container_name: query-handler
    build: ./backend
    env_file:
      - ./backend/.env
    command:
      - "pnpm"
      - "dev:query-handler"
    volumes:
      - ./backend:/app
    depends_on:
      - api
      - event-bus
    networks:
      - db
      - read-db
      - event-bus

networks:
  event-bus:
  db:
  read-db:

volumes:
  database:
  database-read:
  event-bus:

