version: '3.1'

services:
  db:
    image: mysql
    container_name: moneta-flow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'moneta_flow'
      MYSQL_USER: 'moneta_flow'
      MYSQL_PASSWORD: 'Bk55yc1u0eiqga6e'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

volumes:
  database:
