version: '3.1'

services:
  db:
    image: mysql
    container_name: moneta-flow-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'moneta_flow'
      MYSQL_USER: 'moneta_flow'
      MYSQL_PASSWORD: 'Bk55yc1u0eiqga6e'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

  read-db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "moneta_flow"
      MONGO_INITDB_ROOT_PASSWORD: "0sW6pg5Yj0ylM{iy"
    volumes:
      - database-read:/data/db
    ports:
      - 27017:27017
    
volumes:
  database:
  database-read:
