version: "3"

services:
  rabbit: 
    container_name: "microservices_rabbitmq"
    image: "rabbitmq:3-management"
    environment: 
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "123456"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    container_name: "microservices_redis"
    image: 'redis:latest'
    ports:
      - "6379:6379"

