services:
  postgres:
    image: postgres:16-alpine
    container_name: payments-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d payments']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: